spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.PostgreSQLDialect  
    datasource:
        url: "jdbc:postgresql://localhost:5432/blogdb"
        data: "file:src/main/resources/scripts/schema-postgresql.sql"
        username: "bloguser"
        password: "Password123"